### ISSUE TITLE
Error detected while processing function loupe#private#hlmatch..loupe#private#clear_highlight

### ISSUE THREAD

**Issue by lencioni** [wincent/loupe#1]
I'm not entirely sure what I did to get Vim into this state, but when I search for something in any file and press `n` to go to the next result, I get the following message:

```
Error detected while processing function loupe#private#hlmatch..loupe#private#clear_highlight:
line    2:
E803: ID not found: 82
```

Restarting Vim made this stop happening.

**Comment by wincent** [comment]
`:h E803` suggests it's a `matchdelete()` call failing.

I'm guessing some other plug-in, or something else in your set-up, called `clearmatches()` and blew away the highlighting before Loupe could get to it. Any idea what it might have been?

Either way, I think I'll add a `:catch` here to guard against this from happening again.

**Comment by lencioni** [comment]
> Any idea what it might have been?

I don't seem to have anything in my setup that has `clearmatches()` in it, so not really sure. I do recall accidentally pasting a bunch of text into netrw at some point, but I'm pretty sure that made things very weird and I just quit vim and re-opened it right after so that's likely not it either.

**Comment by lencioni** [comment]
I just now saw a similar error, but this time it is E802, and it happens right after pressing `Enter` after typing in a search:

```
Error detected while processing function loupe#private#hlmatch..loupe#private#clear_highlight:
line    2:
E802: Invalid ID: -1 (must be greater than or equal to 1)
```

`:h E802` brings up the same section as `:h E803` so perhaps we should add another catch for E802?

**Comment by wincent** [comment]
Yay for mysterious shit. Thanks for reporting and submitting the PR.
