### ISSUE TITLE
Consider adding live preview

### ISSUE THREAD

**Issue by wincent** [wincent/loupe#10]
Similar to incsearch.vim.

Via the magic of matchadd, perhaps?

This is only a tentative idea; I'm concerned by the complexity of such a feature.

**Comment by damnskippy** [comment]
Now that much of incsearch.vim is[ natively integrated ](https://medium.com/@haya14busa/incsearch-vim-is-dead-long-live-incsearch-2b7070d55250)into vim, this may no longer be necessary?

**Comment by damnskippy** [comment]
That said, one lovely feature that did not get ported that I dearly miss is the ["buffer completion"](https://github.com/haya14busa/incsearch.vim/blob/25e2547fb0566460f5999024f7a0de7b3775201f/doc/incsearch.txt#L289).  I seem to get by for now with [CmdlineComplete](http://www.vim.org/scripts/script.php?script_id=2222), which is not quite the same but similar.

**Comment by wincent** [comment]
Yep, agreed that there is probably not much call for this at this point.
