### ISSUE TITLE
Saner behavior of n and N

### ISSUE THREAD

**Issue by sanpii** [wincent/loupe#16]
https://github.com/mhinz/vim-galore#saner-behavior-of-n-and-n

**Comment by wincent** [comment]
Not clear whether this is a feature request or not, but in case it is:

I don't think I would implement this, even as something gated behind an option: my general policy is to extend and augment Vim, but not to subvert or override in ways that depart from the default behavior in breaking ways. Making `n` and `N` do the _opposite_ of what they would normally do is an example of a breaking change.

Having said that, if you _still_ wanted to do this, you can disable Loupe's standard mappings by setting up a mapping to them in your `.vimrc` (that means that [this line](https://github.com/wincent/loupe/blob/fdbfee0cffe094f0aa7e9039760633380fdb55f8/plugin/loupe.vim#L474) will cause the standard mappings not to be set up). Then in an "after" plugin you set up the alternative mappings that would do what you want.

Example:

```
" in ~/.vim/vimrc (the LHS here is abrbitrary; just make it something you would never press):
nmap <Nop><F1> <Plug>(LoupeN)
nmap <Nop><F2> <Plug>(Loupen)

" in ~/.vim/after/plugin/loupe.vim:
nmap <expr> n (v:searchforward ? "\<Plug>(Loupen)" : "\<Plug>(LoupeN)")
nmap <expr> N (v:searchforward ? "\<Plug>(LoupeN)" : "\<Plug>(Loupen)")
```

If you think this would be useful to other users, we could add it to the docs, but like I said above, it's not something I think I'd add to the core plug-in itself.

**Comment by sanpii** [comment]
Sorry for my unclear message, it was a feature request.

Thank you for your help, I’ll add this to my vimrc.
