### ISSUE TITLE
Help document contains duplicate tags

### ISSUE THREAD

**Issue by paulhybryant** [wincent/loupe#2]
loupe-history duplicates in the documentation, which cause some error messages.

Can considering changing the loupe-overrides (loupe-history, loupe-hlsearch etc) to loupe_history etc in the doc?

Thanks.

**Comment by wincent** [comment]
Sure. What are the error messages? I haven't seen any.

**Comment by paulhybryant** [comment]
The error is the following:

Error generating helptags:
Vim(helptags):E154: Duplicate tag "loupe-history" in file

**Comment by wincent** [comment]
I can't repro the error, but I see the duplicates that you're referring to. I'll remove them. Thanks for the report!

**Comment by paulhybryant** [comment]
Thanks for the quick fix.
