### ISSUE TITLE
very magic not correctly inserted after :g! command

### ISSUE THREAD

**Issue by sebastian-kempf** [wincent/loupe#20]
Noticed this little bug in an otherwise awesome plugin ;) 
If I use the inverted global command  the very magic suffix is appended right after the `:g!` as soon as I type the `!`.  This results in `g!\v` and not the correct `g!/\v`. The `/` is skipped and I need to go back and add it manually.

It's not that big of a deal because you can just use the `:v`-command which does the same thing and works correctly but I didn't want it to go unnoticed either. (Replicated on neovim 0.5, 0.6 and 0.7)

**Comment by wincent** [comment]
Thanks for the report, @sebastian-kempf. I didn't even know `:g!` was a thing, so happy to learn a new Vim factoid. Hopefully the fix will be straightforward; I'll take a look this evening.

**Comment by sebastian-kempf** [comment]
Wow, that was quick!  I can confirm that it works as expected now. Thanks for your great work! 👍🏼
