### ISSUE TITLE
Search mappings like n and N don't open folds

### ISSUE THREAD

**Issue by adriaanzon** [wincent/loupe#9]
When using the search mappings `n`, `N`, `*`, `#`, `g#` or `g*`, and the match happens to be in a fold, the fold doesn't open, unlike the default vim behavior.

I'm on version 7.4.1910 

I think a simple solution would be to add `zv` right below [this line](https://github.com/wincent/loupe/blob/cf57deb36c6ed8ab436861f6e823c650336369b9/plugin/loupe.vim#L430).

**Comment by wincent** [comment]
Thanks for the report. I'd subconsciously noticed this but kept pushing it off. I'll check out your suggested fix and apply it (or something equivalent).
